### ISSUE TITLE
Bucket names with dots in them don't work

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/s3am#11]
For testing I'm just using the public-artifacts.cghub.ucsc.edu bucket which cghub-admin has write permissions to in the us-west-1 region:

s3am upload public-artifacts.cghub.ucsc.edu  https://cghub.ucsc.edu/user_requests/tcga_mc3_broad_preprocessed_cghub_metadata_submitted.tar.gz

this dumps:

(python)STAGE-app01$ s3am upload public-artifacts.cghub.ucsc.edu  https://cghub.ucsc.edu/user_requests/tcga_mc3_broad_preprocessed_cghub_metadata_submitted.tar.gz
Traceback (most recent call last):
  File "/cghub/home/cwilks/bam_slicer/python/bin/s3am", line 8, in <module>
    load_entry_point('s3am==0.1.dev1', 'console_scripts', 's3am')()
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/ui.py", line 17, in try_main
    main( args )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/ui.py", line 33, in main
    upload.upload( )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/upload.py", line 124, in upload
    upload_id, completed_parts = self._prepare_upload( )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/upload.py", line 169, in _prepare_upload
    with self._open_bucket( ) as bucket:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/upload.py", line 63, in _open_bucket
    yield s3.get_bucket( self.bucket_name )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.gaierror: [Errno -2] Name or service not known

**Comment by hannes-ucsc** [comment]
The exception above is most likely caused by dots in the bucket name.

http://blog.chillidogsoftware.com/2013/03/28/fix-for-name-or-service-not-known-error-with-boto/

We are already using the same technique in cgcloud.

**Comment by ChristopherWilks** [comment]
thanks for the quick fix,
however, now I'm seeing this which might be related:

(python)STAGE-app01$ s3am upload cghubtests https://stage.cghub.ucsc.edu/user_requests/C835.HCC1143_BL.4.bam
Traceback (most recent call last):
  File "/cghub/home/cwilks/bam_slicer/python/bin/s3am", line 8, in <module>
    load_entry_point('s3am==0.1.dev1', 'console_scripts', 's3am')()
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/ui.py", line 17, in try_main
    main( args )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/ui.py", line 33, in main
    upload.upload( )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/upload.py", line 124, in upload
    upload_id, completed_parts = self._prepare_upload( )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/upload.py", line 169, in _prepare_upload
    with self._open_bucket( ) as bucket:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/s3am/upload.py", line 63, in _open_bucket
    yield s3.get_bucket( self.bucket_name )
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 654, in make_request
    host = self.calling_format.build_host(self.server_name(), bucket)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 88, in build_host
    return self.get_bucket_server(server, bucket)
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 67, in wrapper
    if len(args) == 3 and check_lowercase_bucketname(args[2]):
  File "/cghub/home/cwilks/bam_slicer/python/lib/python2.7/site-packages/boto/s3/connection.py", line 59, in check_lowercase_bucketname
    raise BotoClientError("Bucket names cannot contain upper-case " \
boto.exception.BotoClientError: BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.

**Comment by hannes-ucsc** [comment]
Chris, the order of arguments in your command line is incorrect. Probably because you were working off the README which had them wrong, too. It's `s3am upload URL BUCKET [KEY]`, not `s3am upload BUCKET URL [KEY]`

Furthermore, there is a better approach to fixing this issue which I committed just now: 

bb244603530f198003dd077807f741dc6343b6e1

You should probably update to that commit unless your buckets are in the Virginia region. Otherwise you'll get a `boto.exception.S3ResponseError: S3ResponseError: 301 Moved Permanently`.

**Comment by ChristopherWilks** [comment]
ok, thanks, that worked on the previous version, and then I updated.

now I've moved on to use the slicer, but now I'm running into a bug where the authorization component is resetting the connection to the slicer, I suspect there's some connection handling bug; we've seen this on production recently as well.
