### ISSUE TITLE
s3am fails with absolute path in source URL

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/s3am#28]
S3am was unable to access the data file for upload when given the path, but when I tried it from within the directory of the data file and just point to the file, it works. 

```
$ s3am upload --sse-key-file /Users/plloyd/s3am/master.key file://Users/plloyd/uploads/DTB-116_Baseline.tar s3://cgl-driver-projects-encrypted/wcdt/plloyd_20160310/
2016-03-17 10:44:47,633 operations(10586) Traceback (most recent call last):
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 465, in _propagate_worker_exception
    yield
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 480, in _stream_part
    buf = self._download_part( part_num )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 521, in _download_part
    c.perform( )
error: (37, "Couldn't open file /plloyd/uploads/DTB-116_Baseline.tar")

2016-03-17 10:44:47,634 operations(10586) Traceback (most recent call last):
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 465, in _propagate_worker_exception
    yield
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 480, in _stream_part
    buf = self._download_part( part_num )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 521, in _download_part
    c.perform( )
error: (37, "Couldn't open file /plloyd/uploads/DTB-116_Baseline.tar")

2016-03-17 10:44:47,635 operations(10586) Traceback (most recent call last):
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 465, in _propagate_worker_exception
    yield
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 480, in _stream_part
    buf = self._download_part( part_num )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 521, in _download_part
    c.perform( )
error: (37, "Couldn't open file /plloyd/uploads/DTB-116_Baseline.tar")

2016-03-17 10:44:47,635 operations(10586) Traceback (most recent call last):
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 465, in _propagate_worker_exception
    yield
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 480, in _stream_part
    buf = self._download_part( part_num )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 521, in _download_part
    c.perform( )
error: (37, "Couldn't open file /plloyd/uploads/DTB-116_Baseline.tar")

2016-03-17 10:44:47,635 operations(10586) Traceback (most recent call last):
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 465, in _propagate_worker_exception
    yield
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 480, in _stream_part
    buf = self._download_part( part_num )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 521, in _download_part
    c.perform( )
error: (37, "Couldn't open file /plloyd/uploads/DTB-116_Baseline.tar")

Traceback (most recent call last):
  File "/Users/plloyd/bin/s3am", line 11, in <module>
    sys.exit(try_main())
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/cli.py", line 37, in try_main
    main( args )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/cli.py", line 80, in main
    result = operation.run( )
  File "/Users/plloyd/s3am/lib/python2.7/site-packages/s3am/operations.py", line 350, in run
    raise WorkerException( )
s3am.WorkerException
```

**Comment by hannes-ucsc** [comment]
The URL should be `file:///Users/plloyd/uploads/DTB-116_Baseline.tar` with three slashes in the beginning.

The error message is 

```
error: (37, "Couldn't open file /plloyd/uploads/DTB-116_Baseline.tar")
```

and not 

```
error: (37, "Couldn't open file /Users/plloyd/uploads/DTB-116_Baseline.tar")
```

because s3am thinks that `Users` is a hostname. Remember that 

`file:///foo/bar` is equivalent to `file://localhost/foo/bar`

`file://foo/bar` to mean ./foo/bar doesn't actually work because `foo` would be interpreted as a host name.

I'll add code to s3am to enforce `file:///` or `file://localhost/` URLs and to allow paths in place of URLs.

Heuristic should be: If argument contains no colon, it must be a path. If it starts with a slash or a dot it must be a path. Otherwise it must be a URL.

**Comment by hannes-ucsc** [comment]
BTW, the issue title sucked ...

**Comment by hannes-ucsc** [comment]
IOW, this is not a bug per-se. Adding above heuristic and stricter argument checking will prevent  misunderstandings like this.

**Comment by Jeltje** [comment]
Or you could be constructive and suggest a better one?

**Comment by hannes-ucsc** [comment]
I did change the title, right after I made that comment so the accusation of me not being constructive is unfounded.

**Comment by Jeltje** [comment]
Yeah sorry, I saw that. Apologies
I was just a little ruffled by the 'sucked' prhasing. It's not always
obvious to us what a good ticket title is, so it seemed a bit petty to
complain about that.

**Comment by hannes-ucsc** [comment]
file:/absolute/path is also ok. IOW, the only disallowed syntax is `file://absolute/path`
