### ISSUE TITLE
libcurl link-time ssl backend error

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/s3am#53]
This is on stacker.pod - I don't know if it's a sysadmin issue or a s3am issue.
I installed s3am in a virtualenv using
`pip install s3am`

But running `s3am` results in 

```
Traceback (most recent call last):
  File "/pod/home/jeltje/s3am/bin/s3am", line 9, in <module>
    load_entry_point('s3am==1.1', 'console_scripts', 's3am')()
  File "/pod/home/jeltje/s3am/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/pod/home/jeltje/s3am/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/pod/home/jeltje/s3am/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/pod/home/jeltje/s3am/lib/python2.7/site-packages/s3am/cli.py", line 24, in <module>
    from s3am.operations import (min_part_size,
  File "/pod/home/jeltje/s3am/lib/python2.7/site-packages/s3am/operations.py", line 28, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (nss) is different from compile-time ssl backend (none/other)
```

**Comment by Jeltje** [comment]
I actually solved it using the info at http://stackoverflow.com/questions/21096436/ssl-backend-error-when-using-openssl

`pip uninstall pycurl`
`export PYCURL_SSL_LIBRARY=nss`
`pip install pycurl`

**Comment by jvivian** [comment]
Did you install all of the dependencies?

`sudo apt-get install python-dev gcc make libcurl4-openssl-dev`

**Comment by Jeltje** [comment]
I don't get to sudo anything on stacker...

**Comment by jvivian** [comment]
aw =( 

You can email Erich about getting Openstack access — We even have an S3-like object store (called Ceph) associated with Openstack.  You get to provision instances like EC2 (where you have sudo privileges).  I ran the I-Spy data on openstack and downloaded / uploaded files to Ceph.

**Comment by hannes-ucsc** [comment]
There is paragraph in the Installation section of the README on this very issue.

**Comment by Jeltje** [comment]
... near the top, too. I should have read. Apologies.
